Vagrant.configure("2") do |config|

  # Configuración del VM1
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "bento/ubuntu-22.04"
    vm1.vm.network "private_network", ip: "192.168.49.3"
    vm1.vm.hostname = "vm1"
  end

  # Configuración del VM2
  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "bento/ubuntu-22.04"
    vm2.vm.network "private_network", ip: "192.168.49.2"
    vm2.vm.hostname = "vm2"
  end

end

